baseURL: ""
relativeURLs: true
title: Michael Lee - Blog
paginate: 5
theme: papermod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-183890003-1

minify:
    disableXML: true
    minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: All essays
          url: /all/
          weight: 5

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Michael Lee - Essays
    description: "Essay is used loosely - these short pieces are my lightly edited thoughts"
    author: Michael Lee

    ShowReadingTime: true
    ShowShareButtons: false
    comments: true
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false
    assets:
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Michael Lee"

    # home-info mode
    homeInfoParams:
        Title: "📕 Essays"
        Content: "Essay is used loosely - these short pieces are my lightly edited thoughts. Email me at michael@biodock.ai"

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        # imageUrl: '<img location>'
        # imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags
    socialIcons:
        - name: linkedin
          url: "https://linkedin.com/in/mike21"
        - name: github
          url: "https://github.com/michaellee1"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
