baseURL: ""
relativeURLs: true
title: Michael Lee - Blog
paginate: 5
theme: papermod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-183890003-1

minify:
    disableXML: true
    minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: All essays
          url: /all/
          weight: 5

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Michael Lee - Essays
    description: "The word 'essay' is used loosely here - these short pieces are my lightly edited thoughts"
    author: Michael Lee

    ShowReadingTime: true
    ShowShareButtons: true
    comments: true
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false
    
    label:
        text: "Michael Lee"

    # home-info mode
    homeInfoParams:
        Title: "📕 Essays"
        Content: >
          The word essay is used loosely - these are my lightly edited thoughts. Email: michael@biodock.ai

          - Are you in debt? Book me [here](https://calendly.com/michael-biodock/zero-cost-debt-consultation) to get my help for free.

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        # imageUrl: '<img location>'
        # imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags
    socialIcons:
        - name: linkedin
          url: "https://linkedin.com/in/mike21"
        - name: github
          url: "https://github.com/michaellee1"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
